services:

    comatrack.listener.kernel_request.tracking:
        class: Chopsol\ContaoMatomoTracker\EventListener\MatomoTracking
        arguments:
            - '@contao.framework'
            - '@session'
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: -50  }

    comatrack.listener.kernel_terminate.tracking:
        class: Chopsol\ContaoMatomoTracker\EventListener\MatomoTracking
        arguments:
            - '@contao.framework'
            - '@session'
        tags:
            - { name: kernel.event_listener, event: kernel.terminate, method: onKernelTerminate, priority: 0  }
